export const DEMO_PROPERTIES = [
  {
    id: "demo-1",
    title: "Modern 2-Bed Apartment in Gulberg",
    address: "123 Main St",
    city: "Lahore",
    area: "Gulberg",
    propertyType: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    monthlyRent: "85000",
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1600&auto=format&fit=crop",
    ],
    isAvailable: true,
    aiSuggestedPrice: "83000",
    coordinates: { lat: 31.5204, lng: 74.3587 },
    landlord: {
      fullName: "Ahsan Ali",
      rating: 4.7,
      reviewCount: 22,
      verificationStatus: "verified",
    },
  },
  {
    id: "demo-2",
    title: "Spacious Family House near DHA",
    address: "45 Park Lane",
    city: "Karachi",
    area: "DHA Phase 6",
    propertyType: "house",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2400,
    monthlyRent: "180000",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1600&auto=format&fit=crop",
    ],
    isAvailable: true,
    coordinates: { lat: 24.8138, lng: 67.0653 },
    landlord: {
      fullName: "Sara Khan",
      rating: 4.8,
      reviewCount: 31,
      verificationStatus: "verified",
    },
  },
  {
    id: "demo-3",
    title: "Commercial Office Space – Blue Area",
    address: "Blue Area",
    city: "Islamabad",
    area: "Blue Area",
    propertyType: "office",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 1200,
    monthlyRent: "140000",
    images: [
      "https://images.unsplash.com/photo-1507209696998-3c532be9b2b1?q=80&w=1600&auto=format&fit=crop",
    ],
    isAvailable: true,
    coordinates: { lat: 33.7205, lng: 73.0606 },
    landlord: {
      fullName: "Blue Area Holdings",
      rating: 4.4,
      reviewCount: 18,
      verificationStatus: "verified",
    },
  },
  {
    id: "demo-4",
    title: "Student Studio near University",
    address: "Hostel Road",
    city: "Lahore",
    area: "Johar Town",
    propertyType: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 450,
    monthlyRent: "35000",
    images: [
      "https://images.unsplash.com/photo-1527030280862-64139fba04ca?q=80&w=1600&auto=format&fit=crop",
    ],
    isAvailable: true,
    coordinates: { lat: 31.4669, lng: 74.2530 },
    landlord: {
      fullName: "Campus Rentals",
      rating: 4.2,
      reviewCount: 12,
      verificationStatus: "verified",
    },
  },
];



